//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingChallenge.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodingChallenge.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.bing.com/maps?rtp=pos.{0}_{1}.
        /// </summary>
        internal static string BingMapLocationLink {
            get {
                return ResourceManager.GetString("BingMapLocationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.bing.com/maps?rtp=pos.{0}_{1}~pos.{2}_{3}.
        /// </summary>
        internal static string BingMapLocationRouteLink {
            get {
                return ResourceManager.GetString("BingMapLocationRouteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao9JjyqYxnOQ5TJ-xOJSUfMdz0G7cj98UuC3f16ybokFxwVI2seTRV5S4Jz73U5O.
        /// </summary>
        internal static string BingMapsKey {
            get {
                return ResourceManager.GetString("BingMapsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding Challenge Form.
        /// </summary>
        internal static string CodingChallengeForm {
            get {
                return ResourceManager.GetString("CodingChallengeForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Data {
            get {
                object obj = ResourceManager.GetObject("Data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input file type ({0}) is not supported..
        /// </summary>
        internal static string FileTypeNotSupportedMessage {
            get {
                return ResourceManager.GetString("FileTypeNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location selection failed.
        /// </summary>
        internal static string LocationSelectionFailed {
            get {
                return ResourceManager.GetString("LocationSelectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon logo_96x96 {
            get {
                object obj = ResourceManager.GetObject("logo_96x96", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Rows: {0}.
        /// </summary>
        internal static string NumberOfRows {
            get {
                return ResourceManager.GetString("NumberOfRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} feet and {1} inches from selected location.
        /// </summary>
        internal static string ResultsToolTip {
            get {
                return ResourceManager.GetString("ResultsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Addresses: .
        /// </summary>
        internal static string SearchAddresses {
            get {
                return ResourceManager.GetString("SearchAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred ({0}) while selecting a new location.  Please try to select another location..
        /// </summary>
        internal static string SelectLocationError {
            get {
                return ResourceManager.GetString("SelectLocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Closest Locations to the selected Location above (closest first).
        /// </summary>
        internal static string TenClosestLocations {
            get {
                return ResourceManager.GetString("TenClosestLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Selected Location in Browser.
        /// </summary>
        internal static string ToolStripMenuLocation {
            get {
                return ResourceManager.GetString("ToolStripMenuLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Selected Route in Browser.
        /// </summary>
        internal static string ToolStripMenuRoute {
            get {
                return ResourceManager.GetString("ToolStripMenuRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        internal static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
